import { Hamburgers } from "@/projects";
import Head from "next/head";

const FreeHamburgers = () => {
  return (
	<>
	<Head>
        <title>Remasters ver2.0.23 - Hamburgers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>	
  	<Hamburgers />
	</>
  );
};
export default FreeHamburgers;