import Footer from 'components/Footer'
import Navigation from 'components/navigation/Navigation'
import ProjectCard from 'components/project-card/ProjectCard'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Remasters ver2.0.23</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
	  <div className=' bg-[#212534]'>
      <main className='py-6 relative min-h-screen text-slate-100'>
	  	<header className='text-center'>
		  <h1 className='text-2xl mb-4'>
			Remasters by {}
			<a href="http://0hundred.dev" className='italic ease-in hover:text-[#ec3389]'
		  	target="_blank" rel="noopener noreferrer">0hundred0</a>
		  </h1>

		  <p className='text-med font-light'>A collection of projects I have made over time, with a few updates.</p>
		</header>
        
		<section className='mt-12 mb-6 px-8 max-w-4xl mx-auto flex flex-wrap justify-evenly'>
			<ProjectCard projectName='DevJokes' projectLink='/devjokes' />
			<ProjectCard projectName='GitAdvice' projectLink='/gitadvice' />
			<ProjectCard projectName='Hamburgers' projectLink='/hamburgers' />
		</section>
		<Footer />
		<Navigation />
      </main>
	  </div>
    </>
  )
}
